# Emotion Face Classifier: EDA Notebook

This notebook is for exploring and understanding the nature of the data.

It will help summarize data and visualize their unique characteristics.

In [4]:
import os
import pandas as pd
import numpy as np

In [2]:
def check_directory_name(target_name) -> bool:
    """
    Check if the current directory name matches the target_name.
    If not, move up a directory and repeat the check.
    
    Args:
        target_name (str): The directory name to match.
        
    Returns:
        bool: True if the current directory name matches the target_name, False otherwise.
    """
    # Get the current directory path
    current_dir = os.getcwd()
    
    # Extract the directory name from the path
    current_dir_name = os.path.basename(current_dir)
    
    # Check if the current directory name matches the target_name
    if current_dir_name == target_name:
        print(f'Directory set to {current_dir}, matches target dir sting {target_name}.')
        return True
    else:
        # Move up a directory
        os.chdir('..')
        # Check if we have reached the root directory
        if os.getcwd() == current_dir:
            return False
        # Recursively call the function to check the parent directory
        return check_directory_name(target_name)

In [3]:
main_dir = 'EmotionFaceClassifier'
check_directory_name(main_dir)

Directory set to /Users/dsl/Documents/GitHub/EmotionFaceClassifier, matches target dir sting EmotionFaceClassifier.

True

In [7]:
df_path = 'data/fer2013/fer2013.csv'
df = pd.read_csv(df_path)

In [15]:
emo_dict = {0:'Angry', 
            1: 'Disgust', 
            2: 'Fear', 
            3: 'Happy', 
            4: 'Sad', 
            5: 'Surprise', 
            6: 'Neutral'}

In [8]:
df.describe()

            emotion
count  35887.000000
mean       3.323265
std        1.873819
min        0.000000
25%        2.000000
50%        3.000000
75%        5.000000
max        6.000000

In [9]:
df.columns

Index(['emotion', 'pixels', 'Usage'], dtype='object')

In [10]:
emo_counts = df.groupby(['Usage', 'emotion']).count()

In [11]:
emo_counts

                     pixels
Usage       emotion
PrivateTest 0           491
            1            55
            2           528
            3           879
            4           594
            5           416
            6           626
PublicTest  0           467
            1            56
            2           496
            3           895
            4           653
            5           415
            6           607
Training    0          3995
            1           436
            2          4097
            3          7215
            4          4830
            5          3171
            6          4965

In [12]:
df.groupby(['Usage']).count()

             emotion  pixels
Usage
PrivateTest     3589    3589
PublicTest      3589    3589
Training       28709   28709

In [14]:
df.groupby(['Usage'])['emotion'].value_counts()

Usage        emotion
PrivateTest  3           879
             6           626
             4           594
             2           528
             0           491
             5           416
             1            55
PublicTest   3           895
             4           653
             6           607
             2           496
             0           467
             5           415
             1            56
Training     3          7215
             6          4965
             4          4830
             2          4097
             0          3995
             5          3171
             1           436
Name: count, dtype: int64